/**
 * The Tailwind v4 bridge.
 *
 * Generates `src/css/theme.generated.css` — a `@theme inline` block plus a small set
 * of `@utility` definitions — from the same token source that produces the legacy
 * custom properties. Nothing here is hand-written, and nothing here contains a
 * literal value: every declaration is a `var()` reference back into the legacy layer.
 * `check-theme.ts` enforces both of those properties.
 *
 * ── Why the `--lg-*` mirrors ──────────────────────────────────────────────────
 * Three token families collide with Tailwind v4's own theme namespaces:
 *
 *   --font-sans / --font-mono          collide with --font-*   (font family)
 *   --shadow-raised / -float / -modal  collide with --shadow-* (box shadow)
 *   --text-strong / -body / -muted …   collide with --text-*   (FONT SIZE)
 *
 * The last is the dangerous one: those are colours, and landing them in the
 * font-size namespace would silently generate broken `text-strong` utilities.
 * Writing `@theme inline { --font-sans: var(--font-sans) }` is also a self-reference.
 *
 * So every legacy token gets a `--lg-`-prefixed mirror, and `@theme` references only
 * mirrors, never legacy names. One rule, no special cases, and a newly added token
 * can never reintroduce the problem.
 *
 * The mirrors are declared here rather than appended to `tokens.css`, so the legacy
 * stylesheet stays exactly what it was for consumers who never touch Tailwind.
 */
import { palette, alias, darkPalette, type PaletteName } from '../src/color.js';
import { family, text, tracking, type TextName } from '../src/typography.js';
import { space, inset, gap, clearanceBar } from '../src/space.js';
import { radius, height, shadow, stroke, dotSeries } from '../src/shape.js';
import { ease, duration } from '../src/motion.js';

/**
 * Semantic aliases get shortened theme keys, because `--color-text-muted` would
 * generate `text-text-muted`. `text-muted`, `bg-card` and `border-hairline` are the
 * names an agent writes correctly on the first try.
 */
export const ALIAS_THEME_KEY: Record<keyof typeof alias, string> = {
  'text-strong': 'strong',
  'text-body': 'body',
  'text-muted': 'muted',
  'text-faint': 'faint',
  'text-on-dark': 'on-dark',
  'surface-card': 'card',
  'surface-field': 'field',
  'surface-quiet': 'quiet',
  'border-hairline': 'hairline',
  'border-strong': 'rule',
  'action-solid': 'solid',
  'action-solid-text': 'solid-text',
  'focus-ring': 'ring',
};

/** Every legacy custom property that gets a mirror, in emission order. */
function mirroredNames(): string[] {
  const names: string[] = [];
  for (const k of Object.keys(palette)) names.push(k);
  for (const k of Object.keys(alias)) names.push(k);
  names.push('font-sans', 'font-mono');
  for (const k of Object.keys(tracking)) names.push(`track-${k}`);
  for (const k of Object.keys(radius)) names.push(`r-${k}`);
  for (const k of Object.keys(height)) names.push(`h-${k}`);
  for (const k of Object.keys(shadow)) names.push(`shadow-${k}`);
  names.push('ease');
  for (const k of Object.keys(duration)) names.push(`dur-${k}`);
  names.push('numeric-data', 'marker');
  return [...new Set(names)];
}

const line = (name: string, value: string) => `  ${name}: ${value};`;
const mirror = (legacy: string) => line(`--lg-${legacy}`, `var(--${legacy})`);

/** px values are literals in the spacing/size namespaces — see the note in emit(). */
const px = (n: number) => (n === 0 ? '0' : `${n}px`);

export function emitTheme(): string {
  const out: string[] = [];

  out.push(`/* Generated by scripts/emit-theme.ts from src/*.ts — do not edit.
   Edit the TypeScript token source and run \`npm run build\`. */`);
  out.push('');
  out.push('@import "tailwindcss";');
  out.push('@import "./tokens.generated.css";');
  out.push('');

  /* ── mirrors ── */
  out.push('/* Mirrors of every legacy token. @theme references these, never the');
  out.push('   legacy names directly — see the header comment for why. */');
  out.push(':root{');
  for (const n of mirroredNames()) out.push(mirror(n));
  out.push('}');
  out.push('');

  /* ── dark theme ── */
  out.push('/* Dark theme: re-point the raw scale, and every utility follows, because');
  out.push('   `@theme inline` keeps the inner var() rather than baking the value. */');
  out.push(':root[data-theme="dark"], .dark{');
  for (const [k, v] of Object.entries(darkPalette)) out.push(line(`--${k}`, v));
  out.push('}');
  out.push('');

  /* ── theme ── */
  out.push('@theme inline {');

  out.push('  /* colour — the raw scale */');
  for (const k of Object.keys(palette) as PaletteName[]) {
    out.push(line(`--color-${k}`, `var(--lg-${k})`));
  }
  out.push('');
  out.push('  /* colour — the semantic aliases components should prefer */');
  for (const k of Object.keys(alias) as (keyof typeof alias)[]) {
    out.push(line(`--color-${ALIAS_THEME_KEY[k]}`, `var(--lg-${k})`));
  }

  out.push('');
  out.push('  /* families */');
  out.push(line('--font-sans', 'var(--lg-font-sans)'));
  out.push(line('--font-mono', 'var(--lg-font-mono)'));

  out.push('');
  out.push('  /* type metrics — family, case and numerics live in the type-* utilities */');
  for (const k of Object.keys(text) as TextName[]) {
    const t = text[k];
    out.push(line(`--text-${k}`, px(t.size)));
    out.push(line(`--text-${k}--line-height`, t.lineHeight === 'normal' ? 'normal' : String(t.lineHeight)));
    out.push(line(`--text-${k}--font-weight`, String(t.weight)));
    if (t.tracking) out.push(line(`--text-${k}--letter-spacing`, `${t.tracking}em`));
  }

  out.push('');
  out.push('  /* tracking */');
  for (const k of Object.keys(tracking)) out.push(line(`--tracking-${k}`, `var(--lg-track-${k})`));

  out.push('');
  out.push('  /* space — named keys, NOT --spacing-1..14: overriding Tailwind\'s numeric');
  out.push('     scale would make p-4 mean 10px and quietly break every muscle-memory class */');
  for (const k of Object.keys(space)) out.push(line(`--spacing-s${k}`, px(space[Number(k) as keyof typeof space])));
  out.push(line('--spacing-gap-tile', px(gap.tile)));
  out.push(line('--spacing-gap-column', px(gap.column)));
  out.push(line('--spacing-board-y', px(inset.board.y)));
  out.push(line('--spacing-board-x', px(inset.board.x)));
  out.push(line('--spacing-card-y', px(inset.card.y)));
  out.push(line('--spacing-card-x', px(inset.card.x)));
  out.push(line('--spacing-row-y', px(inset.row.y)));
  out.push(line('--spacing-clearance-bar', px(clearanceBar)));

  out.push('');
  out.push('  /* control sizes — the spacing namespace feeds h-*, w-*, size-*, p-* */');
  for (const k of Object.keys(height)) out.push(line(`--spacing-${k}`, px(height[k as keyof typeof height])));
  out.push(line('--spacing-meter', px(stroke.meter)));
  out.push(line('--spacing-dot', px(dotSeries)));

  out.push('');
  out.push('  /* radius */');
  for (const k of Object.keys(radius)) out.push(line(`--radius-${k}`, `var(--lg-r-${k})`));

  out.push('');
  out.push('  /* shadow */');
  for (const k of Object.keys(shadow)) out.push(line(`--shadow-${k}`, `var(--lg-shadow-${k})`));

  out.push('');
  out.push('  /* motion */');
  out.push(line('--ease-ledger', 'var(--lg-ease)'));
  out.push('}');
  out.push('');

  /* ── utilities ── */
  out.push('/* The type tokens are a `font` shorthand PLUS tracking PLUS case PLUS');
  out.push('   numerics. Expressing each usage as four utilities is how 0.12em quietly');
  out.push('   becomes 0.1em, so each style ships as one utility carrying all of it.');
  out.push('   Colour is deliberately excluded: `type-label text-faint` is the pair. */');
  for (const k of Object.keys(text) as TextName[]) {
    const t = text[k];
    out.push(`@utility type-${k} {`);
    out.push(line('font-family', `var(--lg-font-${t.family})`).replace('  ', '  '));
    out.push(line('font-size', px(t.size)));
    out.push(line('font-weight', String(t.weight)));
    out.push(line('line-height', t.lineHeight === 'normal' ? 'normal' : String(t.lineHeight)));
    if (t.tracking !== undefined) {
      const named = Object.entries(tracking).find(([, v]) => v === t.tracking);
      out.push(line('letter-spacing', named ? `var(--lg-track-${named[0]})` : `${t.tracking}em`));
    }
    if (t.uppercase) out.push(line('text-transform', 'uppercase'));
    if (t.tabular) out.push(line('font-variant-numeric', 'var(--lg-numeric-data)'));
    out.push('}');
  }

  out.push('');
  out.push('/* Any figure in a table. */');
  out.push('@utility tabular {');
  out.push(line('font-variant-numeric', 'var(--lg-numeric-data)'));
  out.push('}');

  out.push('');
  for (const k of Object.keys(duration)) {
    out.push(`@utility duration-${k} {`);
    out.push(line('transition-duration', `var(--lg-dur-${k})`));
    out.push('}');
  }

  out.push('');
  out.push('/* The highlighter. Once per screen, behind the single sentence that matters. */');
  out.push('@utility marker-highlight {');
  out.push(line('background', 'var(--lg-marker)'));
  out.push(line('box-decoration-break', 'clone'));
  out.push(line('padding', '0.1em 0.25em'));
  out.push('}');

  out.push('');
  out.push('/* Focus is a 2px inset ring, never a browser outline. */');
  out.push('@utility focus-ring-inset {');
  out.push(line('outline', 'none'));
  out.push(line('box-shadow', 'inset 0 0 0 2px var(--lg-focus-ring)'));
  out.push('}');
  out.push('');

  return out.join('\n');
}
