/**
 * Assembles the shipped stylesheets.
 *
 *   dist/tokens.css  — the custom properties alone, for a project that wants the
 *                      design language but brings its own components.
 *   dist/ledger.css  — tokens plus the component class layer. The one file most
 *                      consumers link.
 *
 * Both are flattened rather than left as `@import` chains: a chain costs a
 * request waterfall in the browser and breaks the moment someone copies one file
 * without its siblings. `@import url(...)` for the webfonts is hoisted to the
 * top, because CSS requires every `@import` to precede the first rule.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p: string) => readFileSync(resolve(root, p), 'utf8');

/* The token layer lives in its own package now; read its generated CSS from there
   rather than keeping a second copy in sync. */
const tokensPkg = dirname(fileURLToPath(import.meta.resolve('@ledger/tokens/package.json')));
const readTokens = (p: string) => readFileSync(resolve(tokensPkg, p), 'utf8');

/* Note the greedy `.+`: a Google Fonts URL contains its own semicolons
   (`wght@400;500;600`), so matching up to the FIRST `;` stops mid-URL. */
const IMPORT = /^[ \t]*@import\s+.+;[ \t]*$/gm;

/** Pulls every `@import` out of the body and returns them separately. */
function hoistImports(css: string): { imports: string[]; body: string } {
  const imports = (css.match(IMPORT) ?? []).map((s) => s.trim());
  return { imports, body: css.replace(IMPORT, '').replace(/\n{3,}/g, '\n\n').trim() };
}

const banner = (what: string) => `/* Ledger — ${what}
 * Generated by scripts/build-css.ts. Do not edit; edit src/tokens/*.ts and
 * src/css/components.css, then run \`pnpm build\`.
 */`;

function assemble(what: string, parts: string[]): string {
  const imports: string[] = [];
  const bodies: string[] = [];
  for (const part of parts) {
    const { imports: i, body } = hoistImports(part);
    for (const one of i) if (!imports.includes(one)) imports.push(one);
    bodies.push(body);
  }
  return [banner(what), '', ...imports, imports.length ? '' : null, bodies.join('\n\n'), '']
    .filter((l) => l !== null)
    .join('\n');
}

const tokens = readTokens('src/css/tokens.generated.css');
const components = read('src/css/components.css');

mkdirSync(resolve(root, 'dist'), { recursive: true });

const tokensOut = assemble('design tokens.', [tokens]);
const fullOut = assemble('tokens and components.', [tokens, components]);

writeFileSync(resolve(root, 'dist/tokens.css'), tokensOut);
writeFileSync(resolve(root, 'dist/ledger.css'), fullOut);

const kb = (s: string) => `${(Buffer.byteLength(s) / 1024).toFixed(1)} kB`;
console.log(`css → dist/tokens.css (${kb(tokensOut)})`);
console.log(`css → dist/ledger.css (${kb(fullOut)})`);
